### PR TITLE
ArduinoFiles.h needs to explicitly 'override' virtual methods

### PR DESCRIPTION
**Pull request by mcspr**
Since GCC is very nice and does not force you to write it, and this worked just fine with the provided implementation.
However, GCC ≥13 and -Werror would trigger -Woverloaded-virtual with this impl (testing ESP8266 host builds rn)

Removed method inheritance done with 'using Base = ...' that overlaps with Stream & Print virtuals, plus changed methods in the actual class base.

*(I am also not sure what is the upstream policy on PRs, since the last time I looked everything is just closed immediately :shrug:. but i would wager this would be fixed as soon as gcc is upgrade is more widespread)*

### CODE REVIEW

**Comment by mcspr** [comment]
Not present in https://github.com/earlephilhower/ESP8266SdFat/pull/15 btw, and would break with new formatting :/

**Comment by earlephilhower** [comment]
I'm traveling this week, but will get those in next week when I get home.

**Review by earlephilhower — APPROVED** [review]
Thanks, LGTM.

You still might want to propose these upstream.  Sometimes he won't merge the PR but will do the same changes himself, and these seem harmless and more correct anyway.

**Comment by mcspr** [comment]
> You still might want to propose these upstream. Sometimes he won't merge the PR but will do the same changes himself, and these seem harmless and more correct anyway.

https://github.com/greiman/SdFat-beta/issues/85, pending for the next beta with an additional read(void*, size_t)

From our side only local change is adding
- readBytes(u8, size_t) 
- readBytes(char, size_t)
- read(u8, size_t)

That are missing in ArduinoCore-API proper. But, pretty sure this has to be wrapped in if-def for ESP8266 (as I just noticed that this may break pico build)

**Pull request merged**
